In [1]:
import torch

 # Creating Tensors in PyTorch


In [2]:
# 1. Using tensor
tensor1 = torch.tensor([[1,2,3],[4,5,6]])
tensor1

tensor([[1, 2, 3],
        [4, 5, 6]])

In [3]:
# 2. Using arange function
tensor2 = torch.arange(6).reshape(2,3)
tensor2

tensor([[0, 1, 2],
        [3, 4, 5]])

In [4]:
tensor3 = torch.arange(6,12).reshape(2,3)
tensor3

tensor([[ 6,  7,  8],
        [ 9, 10, 11]])

In [5]:
# 3. Using ones function
tensor4 = torch.ones((2,3))
tensor4

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [9]:
# 4. Using zeros function
tensor5 = torch.zeros((4,5))
tensor5

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [11]:
# 5. Using full function
tensor6 = torch.full((2,3), fill_value=4)
tensor6

tensor([[4, 4, 4],
        [4, 4, 4]])

In [12]:
 # 6. Using empty function
tensor7 = torch.empty(2,3)
tensor7

tensor([[0.0000e+00, 0.0000e+00, 7.7052e+31],
        [1.9447e+31, 2.1715e-18, 2.3081e-12]])

In [13]:
# 7. Using rand function
tensor8 = torch.rand((2,3))
tensor8

tensor([[0.9273, 0.4973, 0.9046],
        [0.4742, 0.8729, 0.1552]])

In [25]:
# 8. Using eye function
tensor9 = torch.eye(4,4)
tensor9

tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])

In [28]:
# 9. Using linspace function
tensor10 = torch.linspace(0,10,8)
tensor10

tensor([ 0.0000,  1.4286,  2.8571,  4.2857,  5.7143,  7.1429,  8.5714, 10.0000])