In [1]:
import torch
import torch.nn as nn

In [8]:
class Model(nn.Module):
  def __init__(self, num_features):
    super().__init__()

    self.linear = nn.Linear(num_features, 1)
    self.sigmoid = nn.Sigmoid()

  def forward(self, num_features):
    out = self.linear(num_features)
    out = self.sigmoid(out)

    return out

In [3]:
features = torch.rand(10, 5)
features

tensor([[0.8850, 0.9562, 0.8432, 0.2632, 0.3732],
        [0.1604, 0.0597, 0.7008, 0.6566, 0.4363],
        [0.2800, 0.3335, 0.7716, 0.2547, 0.7418],
        [0.9097, 0.4813, 0.0165, 0.9463, 0.7124],
        [0.6739, 0.5614, 0.8348, 0.9224, 0.3547],
        [0.4179, 0.9490, 0.7466, 0.9735, 0.8201],
        [0.0861, 0.4340, 0.3475, 0.8288, 0.6189],
        [0.0663, 0.9606, 0.4466, 0.9210, 0.0075],
        [0.3367, 0.8669, 0.9027, 0.7043, 0.9722],
        [0.4574, 0.7641, 0.1799, 0.0366, 0.3737]])

In [9]:
model = Model(features.shape[1])

In [10]:
model(features)

tensor([[0.8020],
        [0.7013],
        [0.7152],
        [0.7716],
        [0.7962],
        [0.8076],
        [0.7182],
        [0.7606],
        [0.7927],
        [0.7112]], grad_fn=<SigmoidBackward0>)

In [11]:
!pip install torchinfo

In [13]:
model.linear.weight

Parameter containing:
tensor([[0.3831, 0.3928, 0.2840, 0.3088, 0.0578]], requires_grad=True)

In [14]:
model.linear.bias

Parameter containing:
tensor([0.3417], requires_grad=True)

In [15]:
from torchinfo import summary
summary(model, input_size=(10,5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 1]                   6
├─Sigmoid: 1-2                           [10, 1]                   --
Total params: 6
Trainable params: 6
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00