In [1]:
!pip install torchinfo

In [3]:
import torch
import torch.nn as nn
from torchinfo import summary

# Architecture Building

In [4]:
class Model(nn.Module):
  # Defining constructor for child class
  def __init__(self, num_features):

    # Calling constructor of super class
    super().__init__()

    # Creating layers of our neural network
    self.linear1 = nn.Linear(num_features, 3)
    self.relu1 = nn.ReLU()
    self.linear2 = nn.Linear(3, 2)
    self.relu2 = nn.ReLU()
    self.linear3 = nn.Linear(2, 1)
    self.sigmoid = nn.Sigmoid()

  # Defining forward pass function
  def forward(self, num_features):
    out = self.linear1(num_features)
    out = self.relu1(out)
    out = self.linear2(out)
    out = self.relu2(out)
    out = self.linear3(out)
    out = self.sigmoid(out)

    return out


# Dataset Creation

In [5]:
data = torch.rand(20,5)
data

tensor([[0.2081, 0.4163, 0.1685, 0.0361, 0.7517],
        [0.7775, 0.5939, 0.0430, 0.7003, 0.4637],
        [0.8500, 0.8783, 0.8617, 0.9992, 0.6830],
        [0.3052, 0.4522, 0.6141, 0.4645, 0.2772],
        [0.7290, 0.0574, 0.4136, 0.5841, 0.9756],
        [0.2335, 0.5935, 0.7257, 0.7430, 0.2905],
        [0.6933, 0.3600, 0.6333, 0.9717, 0.1743],
        [0.3205, 0.4744, 0.5056, 0.5126, 0.9144],
        [0.6891, 0.4434, 0.7159, 0.3098, 0.1198],
        [0.3202, 0.9892, 0.1688, 0.9892, 0.3933],
        [0.4639, 0.1809, 0.8628, 0.0864, 0.4299],
        [0.5947, 0.3687, 0.4471, 0.0235, 0.5847],
        [0.0814, 0.6759, 0.1195, 0.1625, 0.8798],
        [0.2875, 0.7142, 0.8966, 0.7663, 0.5875],
        [0.8737, 0.9415, 0.0907, 0.4904, 0.1166],
        [0.9427, 0.8623, 0.3673, 0.8659, 0.1240],
        [0.4881, 0.2252, 0.4672, 0.7059, 0.7972],
        [0.4717, 0.2371, 0.6056, 0.1312, 0.6460],
        [0.3596, 0.6149, 0.1983, 0.1999, 0.7869],
        [0.5869, 0.5478, 0.7954, 0.3178, 0.9755]])

# Model Creation

In [7]:
model = Model(data.shape[1])

# Applying forward pass

In [8]:
model(data)

tensor([[0.4411],
        [0.4412],
        [0.4415],
        [0.4414],
        [0.4415],
        [0.4415],
        [0.4415],
        [0.4415],
        [0.4411],
        [0.4415],
        [0.4411],
        [0.4410],
        [0.4413],
        [0.4415],
        [0.4410],
        [0.4414],
        [0.4415],
        [0.4411],
        [0.4412],
        [0.4415]], grad_fn=<SigmoidBackward0>)

In [9]:
model.linear1.weight

Parameter containing:
tensor([[-0.2123,  0.1937,  0.4197,  0.4424,  0.2665],
        [ 0.0500, -0.4411, -0.2804,  0.4077,  0.3729],
        [-0.4315,  0.0573, -0.2051,  0.3838, -0.0985]], requires_grad=True)

In [10]:
model.linear1.bias

Parameter containing:
tensor([ 0.0558, -0.2851,  0.3982], requires_grad=True)

In [11]:
model.linear2.weight

Parameter containing:
tensor([[-0.3245,  0.3798, -0.1540],
        [-0.2443, -0.2342, -0.0907]], requires_grad=True)

In [12]:
model.linear2.bias

Parameter containing:
tensor([-0.2610,  0.1912], requires_grad=True)

In [13]:
model.linear3.weight

Parameter containing:
tensor([[-0.1774, -0.0195]], requires_grad=True)

In [14]:
model.linear3.bias

Parameter containing:
tensor([-0.2352], requires_grad=True)

# Model Architecture in diagram form

In [15]:
summary(model, input_size=(20,5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [20, 1]                   --
├─Linear: 1-1                            [20, 3]                   18
├─ReLU: 1-2                              [20, 3]                   --
├─Linear: 1-3                            [20, 2]                   8
├─ReLU: 1-4                              [20, 2]                   --
├─Linear: 1-5                            [20, 1]                   3
├─Sigmoid: 1-6                           [20, 1]                   --
Total params: 29
Trainable params: 29
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00