In [1]:
!pip install torchinfo

In [2]:
import torch
import torch.nn as nn
from torchinfo import summary

In [9]:
class myModel(nn.Module):
  def __init__(self, num_features):
    super().__init__()

    self.linear1 = nn.Linear(num_features, 3)
    self.relu = nn.ReLU()
    self.linear2 = nn.Linear(3, 1)
    self.sigmoid = nn.Sigmoid()

  def forward(self, num_features):
    out = self.linear1(num_features)
    out = self.relu(out)
    out = self.linear2(out)
    out = self.sigmoid(out)
    return out

In [10]:
features = torch.rand(10,5)
features

tensor([[0.7200, 0.9338, 0.5919, 0.6208, 0.0114],
        [0.6442, 0.9721, 0.5436, 0.4153, 0.9092],
        [0.6418, 0.5966, 0.1522, 0.0851, 0.0161],
        [0.3737, 0.3504, 0.6379, 0.4761, 0.9722],
        [0.7863, 0.9869, 0.3166, 0.9373, 0.7024],
        [0.4838, 0.6086, 0.0185, 0.1736, 0.9582],
        [0.8274, 0.6007, 0.4321, 0.1204, 0.9452],
        [0.9563, 0.9100, 0.8280, 0.2326, 0.5817],
        [0.7258, 0.2605, 0.5885, 0.1056, 0.3951],
        [0.6890, 0.8991, 0.6227, 0.2312, 0.3436]])

In [11]:
model = myModel(features.shape[1])

In [12]:
model(features)

tensor([[0.5603],
        [0.5571],
        [0.5603],
        [0.5630],
        [0.5603],
        [0.5563],
        [0.5603],
        [0.5603],
        [0.5603],
        [0.5603]], grad_fn=<SigmoidBackward0>)

In [13]:
model.linear1.weight

Parameter containing:
tensor([[ 0.0662,  0.2539, -0.1485, -0.0743,  0.2827],
        [-0.2438, -0.4213, -0.0955,  0.1255,  0.0554],
        [ 0.0300, -0.1414, -0.3552, -0.3382, -0.2436]], requires_grad=True)

In [14]:
model.linear1.bias

Parameter containing:
tensor([-0.4059,  0.2942, -0.2414], requires_grad=True)

In [15]:
model.linear2.weight

Parameter containing:
tensor([[-0.4527,  0.1021, -0.0178]], requires_grad=True)

In [16]:
model.linear2.bias

Parameter containing:
tensor([0.2423], requires_grad=True)

In [17]:
summary(model, input_size=(10,5))

Layer (type:depth-idx)                   Output Shape              Param #
myModel                                  [10, 1]                   --
├─Linear: 1-1                            [10, 3]                   18
├─ReLU: 1-2                              [10, 3]                   --
├─Linear: 1-3                            [10, 1]                   4
├─Sigmoid: 1-4                           [10, 1]                   --
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00