In [1]:
import torch

In [2]:
tensor1 = torch.arange(10).reshape(2,5)
tensor1

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

# Tensor Shapes

In [3]:
tensor1.shape

torch.Size([2, 5])

In [6]:
# 1. Zeros_like function
tensor2 = torch.zeros_like(tensor1)
tensor2

tensor([[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]])

In [8]:
# 2. ones_like function
tensor3 = torch.ones_like(tensor1)
tensor3

tensor([[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]])

In [10]:
# 3. empty_like function
tensor4 = torch.empty_like(tensor1)
tensor4

tensor([[                  0, 7307199746910528123, 2318330554153050739,
         6877682122580386594, 4121392043054624357],
        [8030888409031647276, 2482735057479098226, 7863883273652543546,
         2477389231675241573, 7020108390734700602]])

# Tensor Data Types

In [11]:
tensor1.dtype

torch.int64

In [12]:
tensor5 = torch.tensor([1,2,3], dtype=torch.float32)
tensor5.dtype

torch.float32

In [14]:
tensor6 = torch.tensor([1.10, 2.20, 3.30], dtype=torch.int16)
tensor6

tensor([1, 2, 3], dtype=torch.int16)

In [15]:
tensor6.dtype

torch.int16

In [17]:
tensor7 = tensor6.to(torch.float32)
tensor7.dtype

torch.float32